API_POOLING_URL = "https://integracao.cardapioweb.com/api/partner/v1/orders"
API_DETALHES_PEDIDO_URL = "https://integracao.cardapioweb.com/api/partner/v1/orders/"
CARDAPIO_API_TOKEN = "8d6mRcvSvtkBVCpUCGSrZ8rriFP35Hd2TvGNSnmG"
EMAIL_USER = "renanalmeida2003@gmail.com"
EMAIL_PASS = "bojjptclmviqipno"
PRINTER_EMAIL = "orleypadaria@print.epsonconnect.com"
